version: '3.8'

services:
  kafka-mongo:
    build:
      context: ./kafka-mongo
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./kafka-mongo:/app 
    networks:
      - app-network

  # poc-attack-server:
  #   build:
  #     context: ./poc-attack-server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8001:8001"
  #   volumes:
  #     - ./poc-attack-server:/app 
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
